@extends('front.layout.app')
@section('content')
<div class="" style="padding:20px 20px;">
   <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eros neque, semper nec facilisis non, vulputate eu justo. Nunc id varius massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent consequat risus blandit odio dictum vestibulum. Aenean venenatis rhoncus ipsum, eget tempus metus laoreet quis. Duis facilisis, enim sit amet dignissim rhoncus, augue tortor pharetra lacus, at fringilla tortor ligula luctus lacus. Vestibulum sit amet iaculis neque. <br><br>
      Mauris eu augue in sem feugiat eleifend sed et mi. Praesent et sem dolor. In mollis euismod metus at interdum. Nullam ut bibendum velit. Duis libero sem, iaculis eget turpis lacinia, vestibulum iaculis tellus. Proin sed fermentum mauris. Curabitur finibus metus magna, volutpat lacinia diam porttitor ac. Sed convallis facilisis dignissim. Mauris sollicitudin tellus vitae ante faucibus suscipit. Maecenas vel tincidunt velit. Aliquam erat volutpat. Vivamus hendrerit tincidunt nisi eget suscipit. Vivamus rutrum ultricies nibh, eget dictum ligula rutrum ut. Ut nisi dui, semper quis tortor sed, tempus tristique mi. Vivamus neque velit, maximus id malesuada ut, varius in tortor.<br><br>
      In a dolor quis nisl lobortis pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum nulla sit amet auctor pulvinar. Fusce eget erat volutpat, scelerisque nisl eu, hendrerit lectus. Phasellus quis auctor dolor. Quisque consectetur leo id luctus ullamcorper. Sed dignissim sem tellus, eu tempus purus semper eu. Suspendisse potenti. Duis pretium, dui ac interdum luctus, odio dui vulputate ipsum, vitae interdum felis tortor ut quam. Aenean semper eu massa sed dignissim. Donec in magna non augue laoreet auctor.<br><br>
      Proin sit amet elit sed sem lobortis volutpat sed et sapien. Morbi dignissim diam molestie eros facilisis, vitae vulputate dolor auctor. Proin consectetur sed felis non mattis. Proin bibendum pellentesque mi quis fringilla. Nulla lacinia urna sit amet orci congue, eget ultrices libero dapibus. Vivamus ultrices turpis at vulputate vulputate. Etiam pellentesque nunc et metus consequat, eu maximus nisi luctus. Nulla fermentum vel velit ac pulvinar. Nunc dapibus est in diam cursus, commodo tempus nisl hendrerit. Sed quis sem erat. Etiam a lorem massa.<br><br>
      Maecenas ultrices sit amet eros quis viverra. Fusce convallis nunc ac ligula rutrum dictum. Suspendisse dictum commodo nisl. Aenean nec augue ultricies, cursus est quis, laoreet sem. Sed in purus eu odio commodo euismod. Vivamus euismod velit eu urna rutrum iaculis. Cras fringilla suscipit odio non blandit. Aenean rutrum turpis urna, eu congue neque vulputate at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam condimentum augue eros, sed vestibulum arcu lobortis id. Pellentesque lorem libero, facilisis id gravida eget, lacinia ut eros. Praesent dapibus, felis eu imperdiet sagittis, quam elit suscipit ex, non pharetra velit mi a eros. Nullam at arcu ac risus blandit interdum a in velit. Morbi at mattis odio. Aliquam eget quam non arcu suscipit tincidunt eget eu eros. Aliquam id arcu consequat, porta nibh in, venenatis magna.
      <br><br>
      Curabitur vitae eleifend elit. Cras feugiat, dui vel iaculis placerat, sem odio porttitor nunc, ac pretium mi mi et elit. Suspendisse odio mi, aliquet sit amet felis quis, mattis iaculis enim. Proin nunc lacus, tempor quis enim eu, auctor elementum diam. Cras volutpat, nisi ut sagittis molestie, sapien mauris tristique arcu, in posuere turpis augue eu nunc. Proin ac ultrices nisi. Integer pretium ornare ante, condimentum tempor nunc sagittis a. Sed ac nibh vitae orci venenatis tincidunt nec faucibus augue. Suspendisse non interdum ipsum, sed ultricies enim. Mauris consectetur velit sit amet magna malesuada, et faucibus quam venenatis. Maecenas ac felis nec leo aliquam interdum in id orci.<br><br>
      Donec aliquet metus eget dolor ullamcorper rhoncus. Donec malesuada, tortor et ornare ornare, augue nisl dapibus elit, at lacinia dui mi vitae turpis. Duis efficitur semper velit, vitae tincidunt risus faucibus vitae. Aliquam malesuada tincidunt aliquet. Integer rutrum enim ex, sed commodo neque aliquam sed. In fringilla lorem non elit consectetur ullamcorper. In pharetra nisl ut ex eleifend sollicitudin. Morbi eleifend volutpat purus convallis scelerisque. Nullam vel sapien augue.<br><br>
      Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ut diam varius, dapibus velit eget, luctus libero. Morbi in suscipit dui. Cras ultricies commodo sem ut auctor. Aliquam et est sit amet dui fringilla porta. Vivamus dapibus maximus lacus ac porta. Ut a odio ac magna consectetur tincidunt eu sit amet nulla. Aenean eu rutrum diam. Integer facilisis vel erat ac blandit. Donec sagittis ante sit amet ligula dictum congue. Vestibulum et nulla commodo, tempus ligula at, pellentesque magna. Sed consectetur non nisl a finibus. Nullam rhoncus elit odio, ut placerat sapien faucibus non. Mauris ornare eget tellus ac lacinia. In cursus pulvinar enim a faucibus. Praesent vehicula nec nisi non rhoncus.<br><br>
      In accumsan id turpis ac placerat. Nunc vel est quis nulla consequat maximus et eu mauris. Vivamus in pellentesque ante. Etiam fringilla enim non consectetur mollis. Nullam ullamcorper sagittis ante, ut dictum nisi placerat at. Duis eu sem ante. Quisque nunc quam, fringilla in luctus vulputate, vestibulum vitae sapien. Sed tempus id lectus eget pretium. Phasellus mollis, purus in iaculis gravida, tellus elit feugiat tortor, in tincidunt justo arcu ac quam. Integer in dignissim odio. Cras tempus elit quis mi lobortis commodo. Etiam elementum quam libero, non pretium neque porttitor a. Fusce efficitur lorem eget augue dapibus, et imperdiet nibh blandit. Duis vel nulla mollis, porttitor risus non, venenatis magna.<br><br>
      Mauris sodales tincidunt bibendum. Proin viverra ac sem non dapibus. Donec vel lacus et dui efficitur accumsan sed et massa. Morbi venenatis vestibulum mi eu accumsan. Vivamus tempus mollis lacus, et porta nisl rutrum in. Vivamus vestibulum, felis eu dictum porttitor, tellus neque volutpat dolor, sit amet porttitor arcu elit sit amet nulla. Nunc posuere erat et sem blandit, tincidunt pharetra nibh tristique. Vestibulum nec dui hendrerit, lobortis metus in, gravida velit. Mauris condimentum aliquam nunc eu sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vulputate diam vitae odio tincidunt, nec eleifend augue ultricies.<br><br>
   </p>
</div>
@endsection